# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-10 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=11, verbose_name='文章标题编号')),
                ('username', models.CharField(max_length=15, verbose_name='用户编号')),
                ('content', models.TextField(max_length=300, verbose_name='评论')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '讨论/提问',
                'verbose_name_plural': '讨论/提问',
                'db_table': 'project_comment',
            },
        ),
    ]
