# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-10 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_id',
            field=models.CharField(max_length=11, null=True, verbose_name='评论编号'),
        ),
    ]
