# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-21 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sgin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, verbose_name='学号')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
            ],
            options={
                'db_table': 'student_sgin',
                'verbose_name_plural': '学生签到',
                'ordering': ['-c_time'],
                'verbose_name': '学生签到',
            },
        ),
    ]
