# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-21 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgin',
            name='stu_name',
            field=models.CharField(max_length=32, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='sgin',
            name='username',
            field=models.CharField(max_length=15, null=True, verbose_name='学号'),
        ),
    ]
