# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-21 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgin', '0002_auto_20190421_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgin',
            name='c_time',
            field=models.CharField(max_length=100, null=True, verbose_name='签到时间'),
        ),
    ]
