# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-22 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgin', '0004_sgin_beizhu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chankan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, null=True, verbose_name='学号')),
            ],
            options={
                'verbose_name': '老师查看学生签到',
                'verbose_name_plural': '老师查看学生签到',
                'db_table': 'teacher_chakan',
            },
        ),
    ]
