# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_username', models.CharField(max_length=15, verbose_name='学号')),
                ('stu_name', models.CharField(max_length=15, null=True, verbose_name='姓名')),
                ('title', models.CharField(max_length=15, verbose_name='标题')),
                ('plan_finish', models.TextField(max_length=5000, null=True, verbose_name='计划完成')),
                ('finished', models.TextField(max_length=5000, null=True, verbose_name='实际完成')),
                ('content', models.TextField(max_length=5000, null=True, verbose_name='问题与计划')),
                ('c_time', models.CharField(max_length=32, null=True, verbose_name='选题时间')),
            ],
        ),
    ]
