# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-24 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekly',
            options={'ordering': ['-c_time'], 'verbose_name': '学生周报', 'verbose_name_plural': '学生周报'},
        ),
        migrations.AlterModelTable(
            name='weekly',
            table='student_weekly',
        ),
    ]
