# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-22 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='文件名')),
                ('headfiles', models.FileField(blank=True, upload_to='files', verbose_name='文件路径')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
        ),
    ]
