# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-22 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='headfiles',
            field=models.FileField(blank=True, upload_to='./files/', verbose_name='文件路径'),
        ),
    ]
