# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-23 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20190422_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='username',
            field=models.CharField(max_length=15, null=True, verbose_name='上传者'),
        ),
        migrations.AlterField(
            model_name='files',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='标题'),
        ),
    ]
