# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-23 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20190423_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='stu_nema',
            field=models.CharField(max_length=32, null=True, verbose_name='上传者姓名'),
        ),
    ]
