# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-23 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_files_stu_nema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='date',
            field=models.CharField(max_length=100, verbose_name='上传时间'),
        ),
    ]
