# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-16 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProject',
            fields=[
                ('pro_id', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='编号')),
                ('pro_title', models.CharField(max_length=40, verbose_name='标题')),
                ('pro_type', models.CharField(choices=[('1', '校内'), ('2', '校外')], default='校内', max_length=32, verbose_name='课题类型')),
                ('pro_teacher', models.CharField(max_length=15, verbose_name='指导老师')),
                ('pro_content', models.TextField(max_length=1000, verbose_name='课题内容')),
                ('pro_count', models.IntegerField(max_length=10, verbose_name='学生选题人数')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('has_confirmed', models.BooleanField(default=False, verbose_name='管理员审核状态')),
            ],
            options={
                'verbose_name': '实训题目',
                'ordering': ['-c_time'],
                'db_table': 'project',
                'verbose_name_plural': '实训题目',
            },
        ),
    ]
