# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-16 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherproject',
            name='pro_count',
            field=models.IntegerField(verbose_name='学生选题人数'),
        ),
    ]
