# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-29 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190429_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaohe',
            name='baogao',
            field=models.IntegerField(max_length=15, verbose_name='实训报告'),
        ),
        migrations.AlterField(
            model_name='kaohe',
            name='count',
            field=models.IntegerField(max_length=15, null=True, verbose_name='总成绩'),
        ),
        migrations.AlterField(
            model_name='kaohe',
            name='kaoqin',
            field=models.IntegerField(max_length=15, verbose_name='考勤'),
        ),
        migrations.AlterField(
            model_name='kaohe',
            name='shixian',
            field=models.IntegerField(max_length=15, verbose_name='系统实现'),
        ),
    ]
