# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-18 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_studentselect'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherproject',
            name='bei_zhu',
            field=models.CharField(max_length=100, null=True, verbose_name='课题审核'),
        ),
        migrations.AddField(
            model_name='teacherproject',
            name='fa_za',
            field=models.CharField(max_length=20, null=True, verbose_name='课题难易程度'),
        ),
        migrations.AddField(
            model_name='teacherproject',
            name='fei_gong',
            field=models.CharField(max_length=300, null=True, verbose_name='学生分工'),
        ),
    ]
