# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-20 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190418_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentselect',
            name='stu_class',
        ),
        migrations.RemoveField(
            model_name='studentselect',
            name='stu_major',
        ),
        migrations.RemoveField(
            model_name='studentselect',
            name='stu_name',
        ),
        migrations.RemoveField(
            model_name='studentselect',
            name='stu_protitle',
        ),
        migrations.RemoveField(
            model_name='studentselect',
            name='stu_teacher',
        ),
        migrations.AddField(
            model_name='studentselect',
            name='fei_gong',
            field=models.CharField(max_length=300, null=True, verbose_name='学生分工'),
        ),
        migrations.AddField(
            model_name='studentselect',
            name='pro_content',
            field=models.TextField(max_length=5000, null=True, verbose_name='课题内容'),
        ),
        migrations.AddField(
            model_name='studentselect',
            name='pro_count',
            field=models.IntegerField(null=True, verbose_name='学生选题人数'),
        ),
        migrations.AddField(
            model_name='studentselect',
            name='pro_teacher',
            field=models.CharField(max_length=15, null=True, verbose_name='指导老师'),
        ),
        migrations.AddField(
            model_name='studentselect',
            name='pro_title',
            field=models.CharField(max_length=40, null=True, verbose_name='实训题目'),
        ),
        migrations.AddField(
            model_name='studentselect',
            name='pro_type',
            field=models.CharField(choices=[('1', '校内'), ('2', '校外')], default='校内', max_length=32, null=True, verbose_name='课题类型'),
        ),
        migrations.AlterField(
            model_name='studentselect',
            name='stu_proid',
            field=models.CharField(max_length=15, unique=True, verbose_name='实训题目id'),
        ),
        migrations.AlterField(
            model_name='studentselect',
            name='stu_username',
            field=models.CharField(max_length=15, verbose_name='学号'),
        ),
    ]
