# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-20 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20190420_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentselect',
            name='pro_type',
            field=models.CharField(choices=[('1', '校内'), ('2', '校外')], default='校内', max_length=32, verbose_name='课题类型'),
        ),
    ]
