# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-20 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20190420_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_jingkuang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, verbose_name='学号')),
                ('stu_name', models.CharField(max_length=32, verbose_name='姓名')),
                ('pro_title', models.CharField(max_length=40, null=True, verbose_name='实训题目')),
            ],
        ),
        migrations.AddField(
            model_name='studentselect',
            name='stu_name',
            field=models.CharField(max_length=15, null=True, verbose_name='姓名'),
        ),
    ]
