# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-20 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20190420_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Select_Over',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuan_username', models.CharField(max_length=15, verbose_name='学号')),
                ('xuan_stu_name', models.CharField(max_length=32, verbose_name='姓名')),
                ('xuan_pro_title', models.CharField(max_length=40, null=True, verbose_name='实训题目')),
            ],
            options={
                'verbose_name_plural': '已经选题',
                'db_table': 'select_ok',
                'verbose_name': '已经选题',
            },
        ),
        migrations.RenameModel(
            old_name='teacher_jingkuang',
            new_name='Select_notok',
        ),
        migrations.AlterModelOptions(
            name='select_notok',
            options={'verbose_name': '尚未选题', 'verbose_name_plural': '尚未选题'},
        ),
        migrations.RenameField(
            model_name='select_notok',
            old_name='pro_title',
            new_name='notok_pro_title',
        ),
        migrations.RenameField(
            model_name='select_notok',
            old_name='stu_name',
            new_name='notok_stu_name',
        ),
        migrations.RenameField(
            model_name='select_notok',
            old_name='username',
            new_name='notok_username',
        ),
        migrations.AlterModelTable(
            name='select_notok',
            table='select_notok',
        ),
    ]
