# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-13 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='工号')),
                ('tea_name', models.CharField(max_length=32, verbose_name='姓名')),
                ('password', models.CharField(max_length=32, validators=['密', '码'])),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='性别')),
                ('emali', models.EmailField(max_length=254, unique=True, verbose_name='电子邮件')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '老师',
                'ordering': ['-c_time'],
                'db_table': 'teacher',
                'verbose_name_plural': '老师',
            },
        ),
    ]
