# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-13 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20190413_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='has_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
