# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-14 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacher_has_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='has_confirmed',
            field=models.BooleanField(default=False, verbose_name='激活状态'),
        ),
    ]
