# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-16 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190414_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密码'),
        ),
    ]
