# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-17 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20190417_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='register_num',
            field=models.CharField(max_length=1000, null=True, verbose_name='注册人数'),
        ),
    ]
